name             'setup'
maintainer       'YOUR_NAME'
maintainer_email 'YOUR_EMAIL'
license          'All rights reserved'
description      'Installs/Configures setup'
long_description 'Installs/Configures setup'
version          '0.1.0'
